name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Generate Changelog
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        ./scripts/release/notes.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: CURRENT-RELEASE-CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
